# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE are ignored when building from the command line, check
# build.gradle files instead.

# When configured, Gradle will run in offline mode and will not download any dependencies from the internet.
#org.gradle.offline=true

# Enables namespacing of each library's R class so that its R class includes only the
# resources declared in the library itself and sees the R classes of the libraries it depends on.
android.useNamespace=true

# SDK Configuration
android.compileSdkVersion=34
android.minSdkVersion=29
android.targetSdkVersion=34

# Build Configuration
org.gradle.jvmargs=-Xmx2048m
org.gradle.daemon=true
org.gradle.parallel=true

# R8/Proguard Configuration
android.enableR8=true
